# Generated by Django 3.1.7 on 2021-05-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('txid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vins', to='blockchain.wallet')),
                ('vout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouts', to='blockchain.wallet')),
            ],
        ),
    ]
