# Generated by Django 3.1.7 on 2021-05-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vins', to='blockchain.wallet'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='vout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouts', to='blockchain.wallet'),
        ),
    ]
