# Generated by Django 3.1.7 on 2021-05-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20210516_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=19)),
                ('total_input', models.DecimalField(decimal_places=10, max_digits=19)),
                ('total_output', models.DecimalField(decimal_places=10, max_digits=19)),
                ('blockhash', models.CharField(max_length=64)),
                ('time', models.TextField()),
                ('blocktime', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.wallet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vins', to='blockchain.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Vout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.wallet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouts', to='blockchain.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
