# Generated by Django 3.1.7 on 2021-05-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20210516_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='data',
        ),
    ]
